### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wuyumin** [gohouse/gorose#1]
1. 使用 Go 依赖管理器（我觉得 Glide 不错 [https://github.com/Masterminds/glide](https://github.com/Masterminds/glide) ）。我看了一下源码，目前已使用几个外部库 github.com/gohouse/utils 和 github.com/go-sql-driver/mysql ，这些外部库可以使用依赖管理器进行管理的，方便用户快速使用。
2. laravel 框架目前是支持MySQL、PostgreSQL、SQLite、SQL Server等数据库，代码架构需要考虑这些吧。
3. 使用GitHub的“projects”进行项目管理规划，这样可以管理TODO及任务安排。

**Comment by fizzday** [comment]
@wuyumin 多谢你的建议, 后期一点点完善, 现在项目才起步, 希望多多支持和提出宝贵的意见

**Comment by wuyumin** [comment]
好的，这个项目的链式调用很不错的。等你把基础架构搭建完毕，我也参与这个项目开发吧。

**Comment by fizzday** [comment]
@wuyumin 好, 我先把各个数据库的驱动给规划好, 然后放入dev分支, 欢迎加入, 希望可以一起做一个更完美的orm
