### ISSUE TITLE
事务中连续更新多个不同的表，默认使用了第一个表名

### ISSUE THREAD

**Issue by yxwyxw3038** [gohouse/gorose#101]
同一个事务中 更新了一个主表 再更新子表   结果却将子表字段更新到了主表, 临时解决方案是设Table(表名)

**Comment by fizzday** [comment]
@yxwyxw3038 可以参考test中的方法
https://github.com/gohouse/gorose/blob/master/orm_execute_test.go#L35

**Comment by yxwyxw3038** [comment]
> @yxwyxw3038 可以参考test中的方法
> https://github.com/gohouse/gorose/blob/master/orm_execute_test.go#L35

我的解决方案也是这样 但是这样好像是种补丁 不太美观

**Comment by fizzday** [comment]
@yxwyxw3038 这个问题解决了, 不需要单独指定表,在事物中也不会存在这个问题了
