### ISSUE TITLE
如何做表同步呢

### ISSUE THREAD

**Issue by nameliba** [gohouse/gorose#102]
同步表结构。

**Comment by fizzday** [comment]
@nameliba 什么意思, 表结构迁移的话, 可以用 `https://github.com/gohouse/converter`

**Comment by nameliba** [comment]
类似于gorm中的

db.AutoMigrate(&User{})

**Comment by nameliba** [comment]
能集成这个使用orm才有意义吧

**Comment by fizzday** [comment]
暂时没有
