### ISSUE TITLE
使用PostgreSQL时Insert()方法占位符问题

### ISSUE THREAD

**Issue by cloudwebrtc** [gohouse/gorose#104]
如题, 当使用map数据源写入数据时
``` go
var data = make(map[string]interface{})
data["name"] = "aab"
data["label"] = "bbb"
data["description"] = "ccc"
if id, err := table.Data(data).InsertGetId(); err != nil {
    logger.Errorf("Db.Save.InsertGetId failed: %v, sql: %s", err, db.LastSql())
}
```
生成的SQL占位符为`($1,$3,$5)`的奇数位:
```sql
INSERT INTO rtc_dial_plan (name,label,description) VALUES ($1,$3,$5), [aaa bbb ccc]
```
期望正确的占位符应为`($1,$2,$3)`

**Comment by cloudwebrtc** [comment]
修复补丁 https://github.com/gohouse/gorose/pull/105

**Comment by eixsky** [comment]
我刚。。 捣鼓了三个小时找到问题所在。。 修改好了。。 跟你补丁差不多思路就是变量用的不一样！
`		for _, key := range insertFields {
			Placeholdertmp:= b.GetPlaceholder()
			if item[key] == nil {
				if operType == "insert" {
					// 放入占位符
					insertValuesSub = append(insertValuesSub,Placeholdertmp)
				}
				// 保存真正的值为null
				b.SetBindValues("null")
			} else {
				if operType == "insert" {
					// 放入占位符
					insertValuesSub = append(insertValuesSub, Placeholdertmp)
				}
				// 保存真正的值
				b.SetBindValues(item[key])
			}
			//insertValues = append(insertValues, "("+strings.Join(insertValuesSub, ",")+")")
			// update
			dataObj = append(dataObj, fmt.Sprintf("%s = %s", key,Placeholdertmp))
		}`
