### ISSUE TITLE
事务里面无法查询，在一定程度上影响了数据的一致性

### ISSUE THREAD

**Issue by xlqroot** [gohouse/gorose#106]
memberWaitingTakePackage := new(MemberWaitingTakePackage)

	orm := engine.NewOrm()

	orm.Begin()

	err = orm.Table(memberWaitingTakePackage).
		Where("package_number","xlq1").
		Where("member_id",1).
		Select()

	if err != nil {orm.Rollback()
		fmt.Println(err)
		return
	}
	fmt.Println(1,memberWaitingTakePackage)
	orm.Commit()

	fmt.Println(2,memberWaitingTakePackage)

1、2都无法获取到数据，初步怀疑是将sql收齐后再向服务器发送的

**Comment by fizzday** [comment]
两种解决方案:
1. 使用 `Get()`或`First()`  
```
	db.Begin()
	res,_:=db.Table(&u).First()
	fmt.Println(res)
	db.Commit()
```
2. 查询用新的对象
```
	var db = DB()
	var db2 = DB()
	var res Users
	db.Begin()
	db2.Table(&res).Select()
	t.Log(res)
	db.Commit()
	t.Log(res)
```

**Comment by xlqroot** [comment]
我这里使用了session的事务，目的是为了在事务里面使用写锁。您的第一种方案是可行的，第二种方案我建议在事务开始前就查询好需要的数据。
