### ISSUE TITLE
where data format is wrong

### ISSUE THREAD

**Issue by dongfenglong** [gohouse/gorose#111]
`filter := gorose.Data{
	"blog_id":blog_id,
	"has_child":0,
}

comments:= []models.Comment{}
o := DB()
err = o.Table(&comments).Fields(slt).Where(filter).Select()`

按照文档https://www.kancloud.cn/fizz/gorose-2/1135840，
给Where传入gorose.Data类型数据结果报错：
where data format is wrong

**Comment by fizzday** [comment]
实测没问题, 能否给一个前后文,或者单独拿出来一个示例做下测试

**Comment by dongfenglong** [comment]
`for k, v := range filter{
			//fmt.Println("k, v =", k, ", ", v)
			o.Where(k, "=", v)
		}`
我给改成这样了用了
