### ISSUE TITLE
调用事务报错，大神帮忙看下

### ISSUE THREAD

**Issue by goodqq140** [gohouse/gorose#114]
gin框架测试orm各项功能，增删改查无问题，测试到事务的时候就报错了，只要调用rollback或commit就panic了，环境：Mac 、go 1.13.6、  gin 1.5.0、gorose 2.1.4

以下是代码：
Router.GET("/commit", func(c *gin.Context) {
		db := models.DB()
		tableName := "admin"
		// 开始事务
		db.Begin()
		data := map[string]interface{}{
			"mobile":   "11111111111",
			"password": utils.Md5("aaa"),
			"name":     "ggyy",
		}

		res, err := db.Table(tableName).Where("id", 6).Data(data).Update()
		if res == 0 || err != nil {
			// 回滚事务
			db.Rollback()
		}
		res2, err2 := db.Table(tableName).Data(data).Insert()
		if res2 == 0 || err2 != nil {
			// 回滚事务
			db.Rollback()
		}
		// 提交事务
		db.Commit()
		c.String(200, "ok")
	})

runtime error: invalid memory address or nil pointer dereference
/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:199 (0x4044e7b)
        panicmem: panic(memoryError)
/usr/local/Cellar/go/1.13.6/libexec/src/runtime/signal_unix.go:394 (0x4044cb8)
        sigpanic: panicmem()
/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:2107 (0x4584ffc)
        (*Tx).rollback: if !atomic.CompareAndSwapInt32(&tx.done, 0, 1) {
/usr/local/Cellar/go/1.13.6/libexec/src/database/sql/sql.go:2126 (0x4684133)
        (*Tx).Rollback: return tx.rollback(false)
/Users/cookies/go/pkg/mod/github.com/gohouse/gorose/v2@v2.1.4/session.go:106 (0x468411d)
        (*Session).Rollback: err = s.tx.Rollback()
/Users/cookies/WWW/gin-admin/route/router.go:245 (0x46ee0ad)
        SetupRouter.func11: db.Rollback()
/Users/cookies/go/src/github.com/gin-gonic/gin/context.go:147 (0x45563ca)
        (*Context).Next: c.handlers[c.index](c)
/Users/cookies/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.3/sessions.go:52 (0x46a43c6)
        Sessions.func1: c.Next()
/Users/cookies/go/src/github.com/gin-gonic/gin/context.go:147 (0x45563ca)
        (*Context).Next: c.handlers[c.index](c)
/Users/cookies/go/src/github.com/gin-gonic/gin/recovery.go:83 (0x456a0b3)
        RecoveryWithWriter.func1: c.Next()
/Users/cookies/go/src/github.com/gin-gonic/gin/context.go:147 (0x45563ca)
        (*Context).Next: c.handlers[c.index](c)
/Users/cookies/go/src/github.com/gin-gonic/gin/logger.go:241 (0x45691e0)
        LoggerWithConfig.func1: c.Next()
/Users/cookies/go/src/github.com/gin-gonic/gin/context.go:147 (0x45563ca)
        (*Context).Next: c.handlers[c.index](c)
/Users/cookies/go/src/github.com/gin-gonic/gin/gin.go:412 (0x456056c)
        (*Engine).handleHTTPRequest: c.Next()
/Users/cookies/go/src/github.com/gin-gonic/gin/gin.go:370 (0x455fc6d)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:2802 (0x4373973)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:1890 (0x436f214)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357 (0x405cee0)
        goexit: BYTE    $0x90   // NOP

[GIN] 2020/03/13 - 19:13:03 | 500 |    3.572032ms |       127.0.0.1 | GET      /commit

**Comment by goodqq140** [comment]
我这边刚测试自动事务也有问题，虽然没有panic但是没有rollback，sql全部执行了
Router.GET("/commit", func(c *gin.Context) {
		db := models.DB()
		tableName := "admin"

		data := map[string]interface{}{
			"mobile":   "11111111111",
			"password": utils.Md5("aaa"),
			"name":     "ggyy",
		}

		err := db.Transaction(
			// 第一个业务
			func(db gorose.IOrm) error {
				_, err := db.Table(tableName).Data(data).Insert()
				if err != nil {
					return err
				}
				_, err = db.Table(tableName).Where("id", 6).Data(data).Update()
				if err != nil {
					return err
				}

				return nil
			},
		)

		c.String(200, fmt.Sprintf("err  :  %v \n\n", err))
	})

**Comment by fizzday** [comment]
@goodqq140 rollback 后需要中断后续代码, 要return, 示例代码:  

```
package main

import (
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"github.com/gohouse/gorose/v2"
	"log"
)

var engin *gorose.Engin

func init() {
	var err error
	engin, err = gorose.Open(&gorose.Config{
		Driver: "mysql",
		Dsn:    "root:123456@tcp(localhost:3306)/novel?charset=utf8mb4",
		Prefix: "nv_",
	})
	if err != nil {
		panic(err.Error())
	}
}
func main() {
	err := trans()
	fmt.Println(err)
}
func get() {
	engin.Use(func(eg *gorose.Engin) {
		eg.SetLogger(gorose.NewLogger(&gorose.LogOption{
			EnableSqlLog:   true,
			EnableSlowLog:  1,
			EnableErrorLog: true,
		}))
	})
	orm := engin.NewOrm()
	res, err := orm.Table("novel").First()
	if err != nil {
		log.Println(err.Error())
	}
	fmt.Println(res)
}

func trans() error {
	var aff int64
	var err error
	db := engin.NewOrm()
	db.Begin()
	aff, err = db.Table("logs").Where("id",11).Update(gorose.Data{"username": "xx1"})
	if err != nil || aff==0 {
		db.Rollback()
		return err
	}
	aff, err = db.Table("logs").Insert(gorose.Data{"username": "xx", "id": 1})
	if err != nil || aff==0 {
			db.Rollback()
			return err
	}
	return db.Commit()
}

```

**Comment by goodqq140** [comment]
我这里试了好几次，加上return后虽然不再panic，也进入到了rollback的判断里面了，也renturn了但rollback之前的所有sql语句还是全部执行了，没有真正的rollback，不知道什么原因，就是这个事务测试不成功

**Comment by fizzday** [comment]
@goodqq140 我反复测试了几次, 都没问题, 无论是成功还是失败, 我用debug追踪了, 每一步执行的返回值都做了不同尝试, 没有问题, 这是测试代码:  

```
package main

import (
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"github.com/gohouse/gorose/v2"
)

func initEngin()*gorose.Engin {
	var err error
	var engin *gorose.Engin
	engin, err = gorose.Open(&gorose.Config{
		Driver: "mysql",
		Dsn:    "root:123456@tcp(localhost:3306)/novel?charset=utf8mb4",
		Prefix: "nv_",
	})
	if err != nil {
		panic(err.Error())
	}
	return engin
}
func main() {
	err := trans()
	fmt.Println(err)
}

func trans() error {
	var aff int64
	var err error
	var engin = initEngin()
	db := engin.NewOrm()
	db.Begin()
	aff, err = db.Table("logs").Where("pkid",11).Update(gorose.Data{"username": "xx123"})
	if err != nil || aff==0 {
		db.Rollback()
		return err
	}
	aff, err = db.Table("logs").Insert(gorose.Data{"username": "xx", "pkid": 1})
	if err != nil || aff==0 {
		db.Rollback()
		return err
	}
	return db.Commit()
}

```

**Comment by goodqq140** [comment]
我套用了你发的这套测试用例，就数据库和表换成我自己的，然后把insert放到update前面，这个代码里测试条件：insert是正确的，update是错误的。以此条件测试，走到update确实return了，但是insert还是执行了，数据库新增了一条数据，按道具来讲后面的update失败了，回滚的时候前面的insert也应该会滚，数据库不应该多那一条新增的数据，我把测试用的代码是数据库贴上来，大神帮忙看下，太诡异了
[orm.zip](https://github.com/gohouse/gorose/files/4332264/orm.zip)

**Comment by fizzday** [comment]
@goodqq140 你用的myisam引擎, 不支持事物

**Comment by goodqq140** [comment]
> @goodqq140 你用的myisam引擎, 不支持事物
吐血，竟然没注意到这方面，实在是惭愧，添麻烦了。。。
