### ISSUE TITLE
dbconfig配置参数不方便存储到外部json/yaml等格式配置文件中，能否改进？

### ISSUE THREAD

**Issue by masuz** [gohouse/gorose#15]
dbconfig配置参数为map[string]interface{}格式，数据库连接配置是map[string]string格式，数据库配置项不固定，很难使用struct进行定义并加载。而且使用json/simplejson等解析工具从外部读取配置文件后，数据库配置项自动变成了map[string]interface{}格式，gorose认为是不正确的配置。能否将配置文件中的数据库配置项改成数组，以方便动态加载并自动适配？如下：

``type DBConfig struct {

    Default string `json:"default"`

    SetMaxOpenConns int `json:"SetMaxOpenConns"`

    SetMaxIdleConns int `json:"SetMaxIdleConns"`

    DBList []map[string]string `json:"dblist"`    \\ 适配可变数据库连接配置，方便进行配置文件持久化

}``

是否可行？

**Comment by fizzday** [comment]
@masuz 其实, 这个问题, 我也考虑过, 因为 tag 会用到reflect, 会影响加载配置的性能, 而在新版中, 为了追求性能, 我们去除了所有的 reflect, 从而使得 gorose 成为 go orm 中执行效率的佼佼者, 所以, 就放弃了一些个性化的用法, 比如: tag

**Comment by fizzday** [comment]
@masuz 目前的做法是有一点简单粗暴了, 接下来, 我们按照你的建议, 做一个兼容的可转换配置, 比如你说的写入json, 但是会采取兼容做法, 不用tag, 再次感谢你的建议

**Comment by fizzday** [comment]
@masuz 现在, 我调整了配置格式, 支持通配配置了, 类似于这样的接收:  
```
// 定义config的struct
	type Configer struct {
		Default         string
		SetMaxOpenConns int
		SetMaxIdleConns int
		Connections     map[string]map[string]string
	}
```
### 参考示例  
```
https://github.com/gohouse/gorose/blob/master/examples/config_from_json.go
```

**Comment by masuz** [comment]
收到，谢谢您！

**Comment by fizzday** [comment]
@masuz 有你的建议, 才能改进的更好, 欢迎提更多更好的建议
