### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1002959f9]

### ISSUE THREAD

**Issue by skyecool** [gohouse/gorose#168]
package main

import (
	"fmt"

	_ "github.com/go-sql-driver/mysql"
	"github.com/gohouse/gorose/v2"
	_ "github.com/mattn/go-oci8"
)

var err error
var engin *gorose.Engin

func init() {
	// 全局初始化数据库,并复用
	// 这里的engin需要全局保存,可以用全局变量,也可以用单例
	// 配置&gorose.Config{}是单一数据库配置
	// 如果配置读写分离集群,则使用&gorose.ConfigCluster{}
	engin, err = gorose.Open(&gorose.Config{Driver: "oci8", Dsn: "root:root@localhost:1521/ORA11G"})
charset=utf8mb4&parseTime=true"})
}
func DB() gorose.IOrm {
	return engin.NewOrm()
}

func main() {

	db := DB()
	

	User := db.Table("BYTE3")
	User.Fields("id, INC_DATETIME").Where("id", ">", 0).Chunk(2, func(data []gorose.Data) error {
		// for _, item := range data {
		// 	fmt.Println(item)
		// }
		fmt.Println(data)

		// 这里不要忘记返回错误或nil
		return nil
	})

}

---------报错-----
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1002959d9]

**Comment by LazyNeo** [comment]
您的邮件我已收到，我会尽快给您回复。
