### ISSUE TITLE
like 模糊查询 SqlLogs日志显示不正确

### ISSUE THREAD

**Issue by A491382** [gohouse/gorose#18]
`count, _ := utils.DB.Table("T_Goods").Where("GoodsName", "like", name).Count()`

期望的sql日志是select count(*) from T_Goods where GoodsName like '%name%' ,

但是通过SqlLogs 发现日志SQL变成 `SELECT count(*) as count FROM T_Goods WHERE  GoodsName like '%!a(MISSING)bc%!'(MISSING) '

真是执行的sql没问题， 但是日志显示有问题
`

**Comment by fizzday** [comment]
@A491382 这个其实是对的, go的 Sprintf 格式化后, 就是这种 !a(xx) 的格式, 相当于是占位分隔符

**Comment by fizzday** [comment]
@A491382 比如, 这一个语句:  
```
db.Query("select * from users where id>? limit ?", 1, 2)
```
会解析成 
```
select * from users where id>? limit ?%!(EXTRA int=1, int=2)
```

**Comment by A491382** [comment]
@fizzday 明白乐， 明白了 ， 谢谢
