### ISSUE TITLE
OrWhere使用not in时报错

### ISSUE THREAD

**Issue by caoyanbin1993** [gohouse/gorose#21]
`func (this *DemoModel)List() (int,[]map[string]interface{},error){
	userM:=this.GetTable()
	count,err := userM.Count("*")
	result,err:=userM.OrWhere("name", "not in", []string{"小米"}).Get()//这里报错
	lastsql := db.LastSql()
	log.Debug(lastsql)
	if(err!=nil){
		return 0,result,err
	}
	this.UseGetter(result)
	return count,result,nil
}`
interface conversion: interface {} is *runtime.TypeAssertionError, not string

使用orWhere时报错，求大大指教。

**Comment by caoyanbin1993** [comment]
不好意思，不知道怎么格式化代码。

**Comment by fizzday** [comment]
这样的吧, markdown语法, 你可以看下代码块的用法就可以了, 非常简单, 就每行3个反引号, 在两行反引号之间写代码就可以了  
```
func (this *DemoModel) List() (int, []map[string]interface{}, error) {
	userM := this.GetTable()
	count, err := userM.Count("*")
	result, err := userM.OrWhere("name", "not in", []string{"小米"}).Get()
	//这里报错 
	lastsql := db.LastSql()
	log.Debug(lastsql)
	if (err != nil) {
		return 0, result, err
	}
	this.UseGetter(result)
	return count, result, nil
}
```

**Comment by fizzday** [comment]
get的返回是 `[]map[string]interface {}`, 所以, 你用她的数据的时候, 在遇到 interface{} 时, 需要指定他的类型

**Comment by caoyanbin1993** [comment]
通过修改collection.Colunm的返回类型，避免了上述错误，谢谢飞哥。
