### ISSUE TITLE
any plan for mongodb drive ?

### ISSUE THREAD

**Issue by CrazyBBer** [gohouse/gorose#25]
this is a strong requriment ,did we have a plan.

**Comment by fizzday** [comment]
目前所有的数据库驱动, 都是使用的 database/sql 接口, 只有驱动是独立的, 而 mongodb 暂时没有对应 database/sql 接口的驱动, 所以, 暂时没法兼容, 除非后续开发出对应的驱动, 或者有人提供了对应的驱动才可以, 目前所有的驱动都放在 `~/gohouse/gorose/drivers` 目录, 有兴趣的, 可以自行在这个目录添加即可
