### ISSUE TITLE
 Insert：no LastInsertId available

### ISSUE THREAD

**Issue by vvhh2002** [gohouse/gorose#26]
我的表结构其实不需要在Inert时返回LastInsertID。
因此建议调整或重载Inert 方法，以便更灵活处理。

**Comment by fizzday** [comment]
我看看, 调整为同意返回影响行数, 然后可以个性化的获取 lastInsertId, 这样是不是要好一些

**Comment by fizzday** [comment]
@vvhh2002 
感谢你的建议, 现已修复为: 默认返回 AffectedRows, 同时, 可以用过db对象获取 LastInsertId

**Comment by brucezhao** [comment]
God！！
我说我的系统怎么突然出问题了！
你的表结构不需要在insert时返回LastInsertID，你直接忽略掉就行了，为什么要把接口的返回值突然改掉呢？
我以前的项目里好多语句都是insert后返回ID，然后在其它地方直接用，今天换了台电脑，重新get了一下，编译出来的系统全部出问题了，这样我得要一个个地去改！
一个稳定的API不能随意修改参数和返回值，这样很容易出问题，而且不好找原因的！有新需求，你完全可以增加新函数啊！
真是被你们这样的随便修改给害死了！！
