### ISSUE TITLE
Execute函数中的stmt没有Close？

### ISSUE THREAD

**Issue by brucezhao** [gohouse/gorose#34]
database.go中的Execute函数中最后一段代码：
	stmt, err := DB.Prepare(sqlstring)
	if err != nil {
		return 0, err
	}
	return dba.parseExecute(stmt, operType, vals)
这个stmt不用Close？
我在一个项目中大量操作数据库，结果产生了Can't create more than max_prepared_stmt_count statements (current value: 16382)这个错误，不知道跟这个stmt没有Close有没有关系。

**Comment by fizzday** [comment]
@brucezhao 可能跟这个有关, 已添加了关闭, 多谢指正

**Comment by brucezhao** [comment]
没有问题了，服务器跑的很平稳了，谢谢！
gorose做的不错！
