### ISSUE TITLE
Update/Insert时数据如何使用数据库表达式？

### ISSUE THREAD

**Issue by masuz** [gohouse/gorose#36]
例如:
`
res, err := db.Table("area").Data(map[string]interface{}{"names": "fizz3", "age": 3, "time": “now()” }).Where("id",10).Update()
`
希望生成的SQL语句：
`Update area set names='fizz3', age=3, time=now() where id=10`
但是目前好像不支持**数据库表达式**，只支持值直接代入。
能否实现类似表达式功能：
`
res, err := db.Table("area").Data(map[string]interface{}{"names": "fizz3", "age": 3, "time": map[string]interface{}{"exp":"now()"}  }).Where("id",10).Update()
`
这个功能还是很实用的，比如用于插入NULL值、直接调用数据库函数或存储过程生成更新值等，否则所有需要表达式的更新都必须写原生SQL不方便。
谢谢！

**Comment by fizzday** [comment]
@masuz 欢迎一起协作, 改进源码
