### ISSUE TITLE
你们怎么可以随便修改函数的返回值？？

### ISSUE THREAD

**Issue by brucezhao** [gohouse/gorose#38]
今天换了台电脑，重新get了gorose，发现编译出来的系统出问题了，跟踪发现insert返回的值始终为1，而不是原来的LastInsertID了！
我系统中用到了大量的Insert，然后获得返回的ID在其它地方使用，现在突然全部要改了，还得小心不要漏了哪里。
做为一个稳定的系统，API是不应该允许随便修改参数和返回值，有新需求应该增加新函数来完成，而不是修改原来的函数，这样很容易导致老代码出问题的，有时候真会害死人啊！

**Comment by fizzday** [comment]
@brucezhao 额, 这个非常抱歉, 如果你用了版本管理, 可以很好的解决这个问题, 后来api完善, 做了长久性的调整  
这里有版本更新日志: https://github.com/gohouse/gorose#release-notes  
```
0.9.1
replace the insert result lastInsertId with rowsAffected as default
```
也就是说, 你使用此版本之前的, 都不会有问题  
另外, 这里返回id会存在致命bug, 比如, 表没有自增id, 甚至没有主键, 还望见谅. 所有的改进, 都是为了更好更长久的发展  
目前还没有发布一个 realease 版本, 也是想慢慢发展成熟后, 给一个负责任的 realease 版本

**Comment by fizzday** [comment]
@brucezhao orm新增了 InsertGetId() 快捷方法, 可以满足需求, insert => insertGetId
