### ISSUE TITLE
同时使用多个连接配置，每次都要重新Open一个新配置？

### ISSUE THREAD

**Issue by haowanxing** [gohouse/gorose#39]
一个简单的例子：业务逻辑需要用到多个库（或用户），这可以在ConnectionConfigs里面配置。但是每次到切换配置时，都会用Open去建立一个新的Connection来覆盖之前Connect全局变量，之前的Connection则被“丢弃”。

PS:一开始我以为gorose.Open()会返回一条新的Connection，所以我使用map将配置对应的Connection关联，这样就不用重复Open相同的配置，结果不行，发现map中的Connection都是同一个（且最后一次Open的那个）；接着尝试GetInstance()来返回一个新的DataBase指针，利用Map对应配置，最后发现所有的DataBase指针都会去找那个全局的Connet变量。故，提出问题，望得到正解！

**Comment by fizzday** [comment]
@haowanxing 谢谢你的提问, 现已发布新版本 `0.9.2`, 对这个问题做了完善的改进, 并且做了一个使用示例, 在示例目录文件中 [https://github.com/gohouse/gorose/blob/master/examples/multiConnection.go](https://github.com/gohouse/gorose/blob/master/examples/multiConnection.go)

**Comment by haowanxing** [comment]
@fizzday gorose.go line: 7 引用了另外一个项目"kuaixinwen"中的utils，而非当前项目的utils。且当前项目utils缺少ParseInt方法

**Comment by fizzday** [comment]
@haowanxing 多谢指出, 早上更改, 没有注意, 把本地库纳入到了版本中
