### ISSUE TITLE
Page和Count方法会进行配套是用，但其各自都会进行Reset操作

### ISSUE THREAD

**Issue by luispater** [gohouse/gorose#4]
同一个connection中，再一次db.Table也没有帮助，看了代码，貌似是一个connection中，对象只创建一次，需要重新创建一个connection，才可以解决这个问题。
而Page和Count经常是配套使用的（原因很简单，要分页，总要知道分页的总数），Page了以后Get等方法也同样会Reset查询，甚至Count的时候也会进行Reset

**Comment by fizzday** [comment]
- Firstly, thanks for your issue. Next, we shall working on this issue , and expect a better solution .   
- moreover ,If you have some good ideas, you can share it with us. Or make a pull requests for improving the open source orm

**Comment by fizzday** [comment]
@luispater @luispater 发布了0.8.1, 解决了这个问题
