### ISSUE TITLE
支不支持json字段的提取？

### ISSUE THREAD

**Issue by zbird** [gohouse/gorose#43]
支不支持json字段的提取？

**Comment by fizzday** [comment]
@zbird https://github.com/gohouse/gorose/blob/master/examples/json_field.go, 这里有使用json的示例

**Comment by zbird** [comment]
恩，了解了。但是没见你的test对应的struct定义？
比方说
type Inner struct {
  ID   int
  Name string
}

type Test struct {
       InnerObj Inner   `gorose: json`
}

**Comment by fizzday** [comment]
@zbird 这里有两种用法, 一种是struct定义表结构用法, 另一种是无须定义表结构, 直接使用表名 string就可以了, 1.x版本, 同时支持这两种

**Comment by zbird** [comment]
没关系，我拉下来，看看自己实现了，然后share给你们

**Comment by fizzday** [comment]
@zbird 这个感情好, 可以共同维护
