### ISSUE TITLE
LIKE的时候 为什么会格式化成这样的SQL？

### ISSUE THREAD

**Issue by ghost** [gohouse/gorose#45]
为什么会格式化成这样的SQL？
![image](https://user-images.githubusercontent.com/13595898/44252649-70892980-a22f-11e8-8532-4ae00fc19f9b.png)

![image](https://user-images.githubusercontent.com/13595898/44252667-7bdc5500-a22f-11e8-8cae-565327c4da85.png)

**Comment by fizzday** [comment]
这个是 printf 格式换后的sql, 真正执行的, 是没有格式化的sql, 所以, 不用担心

**Comment by meizhaorui** [comment]
in file database.go
change 
```go
dba.LastSql = fmt.Sprintf(sqlstring, vals...)
```
to
```go
dba.LastSql = fmt.Sprintf(strings.Replace(sqlstring, "%", "%%", -1), vals...)
```
