### ISSUE TITLE
Get方法调用之后没有Reset吗？

### ISSUE THREAD

**Issue by xiaoqingping** [gohouse/gorose#49]
版本0.9.2 
`db.Table("user").Fields("*").Where("user_id", id).Get()`
id通过传参赋值，每次传入不同的id，可以看到打出来的LastSql也保存了之前所有传入的id。
看了Get的实现，没有在执行完成之后进行重置。

**Comment by fizzday** [comment]
@xiaoqingping 这里考虑到多出调用where, 所以采用的是where条件叠加, 如果要重置where, 有两种实现方法:  
1. 手动重置:  `db.ResetWhere()`  
2. 新建会话:  `connection.NewDB()`  

这两种操作都会得到空where
