### ISSUE TITLE
Reset方法将this.trans = false，导致事务无效

### ISSUE THREAD

**Issue by luispater** [gohouse/gorose#5]
db.Begin以后，进行任何的查询，都会调用Reset方法，this.trans = false使得剩余的查询使用stmt, err := DB.Prepare(sqlstring)，而非stmt, err := Tx.Prepare(sqlstring)。
既然起了事务，应保持用户在commit或rollback之前在同一个连接中继续使用事务，而不应该粗暴的将this.trans设置为false

**Comment by luispater** [comment]
我的解决方法是将Reset方法中this.trans = false注释掉

**Comment by fizzday** [comment]
@luispater 目前已经有解决方案了, 明天会发布新版本

**Comment by fizzday** [comment]
@luispater 发布了0.8.1, 解决了这个问题
