### ISSUE TITLE
EnableQueryLog  是不是没起作用啊

### ISSUE THREAD

**Issue by weichangdong** [gohouse/gorose#54]
getLastSql  升级之后 没有了么?
怎么降级啊?

**Comment by fizzday** [comment]
@weichangdong 多谢指出, 现在把开关启用了, 因为新版bug反馈阶段, 方便调试, 之前就没有启用开关

**Comment by fizzday** [comment]
@weichangdong  NewSession之后, 是一个会话整体, where会叠加的, 如果想全新where, 可以再 NewSession, 或者直接使用 connection.Table()这就是一个全新的
