### ISSUE TITLE
go mod 引用不了

### ISSUE THREAD

**Issue by objcoding** [gohouse/gorose#55]
require github.com/gohouse/gorose v1.0.0，报 unknown revision v1.0.0，但你的tag是有这个版本的

**Comment by fizzday** [comment]
@objcoding 不能使用v1.0.0, 要使用 1.0.0, 看来我是不是要tag标准化, 改成 v1.0.0呢, 是否有好的建议

**Comment by objcoding** [comment]
我觉得是有必要改成 v1.0.0，毕竟这也是go mod 规范的地方，如果以后有 v2，则可以在go mod 文件中第一行 modules  github.com/gohouse/gorose/v2 这样表示，同样是 v 开头表示版本号。

**Comment by fizzday** [comment]
@objcoding 恩, 我改一下吧, 0.x版本就不管了

**Comment by objcoding** [comment]
而且，你这样表示，同样会报错， github.com/gohouse/gorose@v0.0.0-20180925034419-fbe0601b81b5: parsing go.mod: go.mod:5: usage: require module/path v1.2.3

**Comment by objcoding** [comment]
@fizzday 期待！
