### ISSUE TITLE
Can't create more than max_prepared_stmt_count statements

### ISSUE THREAD

**Issue by weichangdong** [gohouse/gorose#58]
并发大的时候,报错.

**Comment by fizzday** [comment]
max_prepared_stmt_count 取决于这个值得大小, 根据你的数据库配置有关

**Comment by weichangdong** [comment]
我开始使用的应该是0.83的吧,现在升级到了0.93,暂时没出现了.

**Comment by fizzday** [comment]
@weichangdong 可以使用最新版1.x, 有更多特性

**Comment by weichangdong** [comment]
上次我用了1.x版本,发现你那个session有点不好用,就是造成where条件append的问题.所以......
