### ISSUE TITLE
使用Count的时候 返回值为nil 报错

### ISSUE THREAD

**Issue by cgsunshine** [gohouse/gorose#59]
interface conversion: interface {} is nil, not int64   返回之前 判断一下  是不是nil 再转int64
老哥

**Comment by fizzday** [comment]
@cgsunshine  底层驱动在没有数据的时候返回的是0, 你这个nil是在什么情况下出现的, 能否提供一下用法示例呢, 以便彻底排查清楚问题并解决, 谢谢

**Comment by cgsunshine** [comment]
order, err3 := connect.Table("order").Where("memberuuid", uuid).Count()
如果查不到值 就报错 改了之后是这样
// Count : select count rows
func (dba *Session) Count(args ...string) (int64, error) {
	fields := "*"
	if len(args) > 0 {
		fields = utils.ParseStr(args[0])
	}
	count, err := dba.UnionAct("count", fields)
	if count == nil {
		count = int64(0)
	}
	return count.(int64), err
}

**Comment by fizzday** [comment]
@cgsunshine 恩, 我复现了这个错误, 当我把字段名字写错的时候, 就会panic错误, order的值确实为nil, 多谢指出, 这里没有做严谨性判断, 你可以把这段代码提一个 pr , 我合并到主分支, 也算是你参与的一部分
