### ISSUE TITLE
有个比较低级的错误

### ISSUE THREAD

**Issue by luispater** [gohouse/gorose#6]
utils/util.go中的AddSingleQuotes有2个问题
一个是启用了stmt，但是仍然是通过拼接SQL，这部分就不展开说了，但是在数据的外层添加单引号以后，数据内部的单引号没有被替换掉，导致执行SQL直接出错。
另外一个在对数据加单引号的时候，竟然先对数据进行了trim……如果我就是想在数据库中保存空格怎么办？
代码修改如下：
return "'" + strings.Replace(ParseStr(data), "'", "\\'", -1) + "'"

**Comment by fizzday** [comment]
@luispater 多谢您提出的宝贵建议, 目前添加单引号已改进为
```
return "'" + strings.Replace(ParseStr(data), "'", `\'`, -1) + "'"
```
这里使用了反引号来转义反斜杠, 用双引号会报错  

至于 stmt 的拼接sql, 我们会作为后续升级的改进并完善, 现阶段有官方底层的sql防注入机制, 不会有大的影响
