### ISSUE TITLE
go get -u -v -x github.com/gohouse/gorose

### ISSUE THREAD

**Issue by yezihack** [gohouse/gorose#64]
fatal: No url found for submodule path 'docs/gorose' in .gitmodules
package github.com/gohouse/gorose: exit status 128

**Comment by fizzday** [comment]
@yezihack  这个是版本升级导致的(0.x -> 1.x), 只需要删除 github.com/gohouse/gorose 目录, 重新 go get github.com/gohouse/gorose 即可
