### ISSUE TITLE
go get error!

### ISSUE THREAD

**Issue by ZhiweiWang** [gohouse/gorose#66]
run:

go get -u github.com/gohouse/gorose

get:

# cd /Users/petaflops/work/golang/src/github.com/gohouse/gorose; git submodule update --init --recursive
fatal: No url found for submodule path 'docs/gorose' in .gitmodules
package github.com/gohouse/gorose: exit status 128

**Comment by fizzday** [comment]
@ZhiweiWang  说明你本地有0.x版本, 彻底删除后, 重新下载即可, 1.0移除了 docs/gorose
目录, 所以会报这个问题

**Comment by ZhiweiWang** [comment]
谢谢，我fork了一个，删掉了那个文件夹，然后做了新的release才成功装上
