### ISSUE TITLE
嵌套查询好像不好用。

### ISSUE THREAD

**Issue by ghostljj** [gohouse/gorose#68]
嵌套查询好像不好用。
`	

	User := ConnectionMS.NewSession().Table(t.TableName())
	User.Where("name", ">", 1)
	User.Where(func() {
		User.OrWhere("name", "fizz").OrWhere(func() {
			User.Where("name", "fizz2").Where(func() {
				User.Where("name", "fizz53").OrWhere("website", "like", "fizzday%")
			})
		})
	})

	fmt.Println(User.BuildSql())
`

居然生成SELECT * FROM T_Room_Order WHERE name > 1 and () 

是不是有什么bug

**Comment by ghostljj** [comment]
解决办法。。。
query.Where(`(IsStop is null or IsStop=0) and 1`, 1)

**Comment by ghostljj** [comment]
感觉这个插件确实好用，只是好像还没完善

**Comment by fizzday** [comment]
@ghostljj 这个是0.x版本开发的功能, 后来升级1.x做了结构变动, 没有注意到, 这个功能确实有bug, 后续版本改进下

**Comment by ghostljj** [comment]
> @ghostljj 这个是0.x版本开发的功能, 后来升级1.x做了结构变动, 没有注意到, 这个功能确实有bug, 后续版本改进下

麻烦麻烦。除了这个，还有left join 应该也不支持嵌套 ，不敢试，都直接写语句了。

**Comment by fizzday** [comment]
@ghostljj 恩, 暂时不要试用嵌套查询

**Comment by fizzday** [comment]
2.0版本已发布, 已解决此问题
