### ISSUE TITLE
utils.AddSingleQuotes

### ISSUE THREAD

**Issue by yangyuclub** [gohouse/gorose#71]
utils.AddSingleQuotes 这个里只对单引号进行了转义， 反斜杠没有转义，导致插入内容中的反斜杠丢失了
gorose v1.0.4

我只能自己加了个预处理函数
```
func AddSlashes(str string) string {
	str = strings.Replace(str, "\\", "\\\\", -1)
	str = strings.Replace(str, "\"", "\\\"", -1)
	return str
}
```

相关资料: https://www.yangyu.club/p-251.html

**Comment by fizzday** [comment]
@yangyuclub 多谢指出, 可以提交pr改进

**Comment by quzhi78** [comment]
'STITSSQUASHED,MASHEDANDPUNISHED!

**Comment by quzhi78** [comment]
遇到类似问题,插入数据时没有做转义, PostgreSQL 11.x下会捕获到异常
Value: "'S.w!"

**Comment by yangyuclub** [comment]
@fizzday  已经做好pr ：  https://github.com/gohouse/gorose/pull/74
