### ISSUE TITLE
gorose 2.0 版本开发计划讨论

### ISSUE THREAD

**Issue by fizzday** [gohouse/gorose#73]
# 2.0版本规划

## 开发计划
按照 laravel 的数据库操作 query builder 的标准开发, 同时可酌情添加 eloquent 的部分设计思想和 api

## 产品规划
采用模块分离的方式, 每个模块以 接口 的方式相互调用, 做到模块相互独立, 后期可以自由方便的拓展.  
比如驱动, 不同驱动的sql构建

## 设计目标
每个模块要做到可以自由横向扩展, 以实现个性化需求.  
比如返回结果: map, struct, 自定义数据类型等.  

## 模块大致结构图
![gorose_2.0](https://github.com/gohouse/gorose/blob/2.0-dev/version_plan_and_design/gorose_2.0_modules.png?raw=true)

**Comment by solarhell** [comment]
希望能加入`context`支持。

**Comment by fizzday** [comment]
@solarhell 可以说说具体实现的形式和方式, 最好给出使用时的样例

**Comment by solarhell** [comment]
现在事务用起来，跨函数或者跨service挺难管理的，如果原生能够通过`context`来支持，或许用起来会更优雅。

**Comment by fizzday** [comment]
@solarhell 是想通过context统一处理状态是吧

**Comment by RoseEnd** [comment]
目前貌似没有看到关于模型关系的规划？
