### ISSUE TITLE
开启事务时，select也需要切换到master

### ISSUE THREAD

**Issue by yangyuclub** [gohouse/gorose#82]

**Comment by fizzday** [comment]
有时候, master库是只写, 不能读, 这种情况, 有什么好的处理措施呢

**Comment by yangyuclub** [comment]
没有只能写不能读的主库
只有不能写只能读的从库

**Comment by fizzday** [comment]
好的, 多谢指出, 我修整一下

**Comment by fizzday** [comment]
> 没有只能写不能读的主库
> 只有不能写只能读的从库

已经修正为, 事务中, 从主库读. 不过, 一般来讲, 从库读也是没问题的, 因为启动事务的时候, 是会锁定对应的行, 其他人也修改不了, 只要主从没有夸张的延迟, 基本没啥问题. 当然, 严格理论上, 还是有可能的.   
跟我们dba讨论了下这个问题, 他说中间件会过滤这种问题, 所以, 有时候会严格限制不能从主库读.  不过, 我们既然做了代码层面的读写分离 , 还是更多考虑代码端好一点. 

总之, 谢谢你的建议 ^_^ , 再过段时间, 完善的差不多了, 就可以发正式版本了
