### ISSUE TITLE
the placeholder of oracle is  :%v

### ISSUE THREAD

**Issue by icefoxhz** [gohouse/gorose#87]
builder_default.go   =>  GetPlaceholder()  

增加oracle占位符
// GetPlaceholder 获取占位符
func (b *BuilderDefault) GetPlaceholder() (phstr string) {
	switch b.driver {
	case "postgres":
		withLockContext(func() {
			ph := b.placeholder + 1
			phstr = fmt.Sprintf("$%v", ph)
			b.placeholder = ph
		})
	case "oci8":
		withLockContext(func() {
			ph := b.placeholder + 1
			phstr = fmt.Sprintf(":%v", ph)
			b.placeholder = ph
		})
	case "mysql":
		phstr = "?"
	default:
		phstr = "?"
	}
	return
}

**Comment by fizzday** [comment]
@icefoxhz   oracle占位符, 我查了下, 貌似长这样 
```
insert into dept values(:num,:name,:loc)
```
是具体命名占位符, 而你给出的示例, 是类同 pg 的占位符 `$1`, `$2`这种一次递增的.  
是否修复为命名字段, 方可正常工作

**Comment by icefoxhz** [comment]
恩~不需要递增~~  不重复就可以了~  


------------------ 原始邮件 ------------------
发件人: "飞哥(fizzday)"<notifications@github.com>;
发送时间: 2019年8月13日(星期二) 中午11:46
收件人: "gohouse/gorose"<gorose@noreply.github.com>;
抄送: "爆裂天使"<85972652@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [gohouse/gorose] the placeholder of oracle is  :%v (#87)




@icefoxhz   oracle占位符, 我查了下, 貌似长这样
 insert into dept values(:num,:name,:loc)  
是具体命名占位符, 而你给出的示例, 是类同 pg 的占位符 $1, $2这种一次递增的.
 是否修复为命名字段, 方可正常工作
