### ISSUE TITLE
oracle 语法没有 limit

### ISSUE THREAD

**Issue by icefoxhz** [gohouse/gorose#89]
如果要支持oracle，涉及到 limit 的部分需要修改~~

builder_default.go 

func (b *BuilderDefault) BuildLimit() string {
	if b.IOrm.GetUnion()!=nil {
		return ""
	}

	var limitStr string
	switch b.driver {
	case "oci8":
		if len(b.IOrm.GetWhere()) > 0 {
			limitStr = " AND ROWNUM<="+strconv.Itoa(b.IOrm.GetLimit())
		}else{
			limitStr = " WHERE ROWNUM<="+strconv.Itoa(b.IOrm.GetLimit())
		}
	default:
		limitStr = " LIMIT "+strconv.Itoa(b.IOrm.GetLimit())
	}
	return If(b.IOrm.GetLimit() == 0, "", limitStr).(string)
}

以上修改后，oracle的 Chunk 操作还是有问题~~还需处理~~

**Comment by fizzday** [comment]
@icefoxhz 其实, 我把每个驱动单独放一个问题, 就是为了后续可以直接独立写sql构造器, default只是在没有的时候做一个默认选项, 目前还没有完善Oracle, 因为没有用过, 不太熟悉, 建议只使用与mysql兼容的部分, 不兼容部分建议使用原生sql. 

同时, 希望可以帮助完善Oracle sql构造器

**Comment by icefoxhz** [comment]
恩恩~~   我这是临时应急用~~



------------------ 原始邮件 ------------------
发件人: "飞哥(fizzday)"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 下午5:13
收件人: "gohouse/gorose"<gorose@noreply.github.com>; 
抄送: "爆裂天使"<85972652@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [gohouse/gorose] oracle 语法没有 limit (#89)




@icefoxhz 其实, 我把每个驱动单独放一个问题, 就是为了后续可以直接独立写sql构造器, default只是在没有的时候做一个默认选项, 目前还没有完善Oracle, 因为没有用过, 不太熟悉, 建议只使用与mysql兼容的部分, 不兼容部分建议使用原生sql.
 
同时, 希望可以帮助完善Oracle sql构造器
