### ISSUE TITLE
操作oracle数据库时，Limit()方法会出现错误

### ISSUE THREAD

**Issue by dxvgef** [gohouse/gorose#96]
以为Limit(10)可以实现，结果出现类似"sql: expected 2 destination arguments in Scan, not 1"的错误提示，自己用Where("rownum<10")才行

**Comment by fizzday** [comment]
@dxvgef Oracle对应的api驱动解析是一个群员维护的, 你可以找他沟通下, 也可以在贡献记录里看到贡献人员是谁

**Comment by icefoxhz** [comment]
可以把整句链式操作发出来吗？ 我这测试是可以的

**Comment by icefoxhz** [comment]
可以使用  db.LastSql()  查看生成的 sql语句~~

**Comment by dxvgef** [comment]
> 可以使用 db.LastSql() 查看生成的 sql语句~~
关键代码在这个地方
```go
	var rows []model.TestTable
	db := engin.NewOrm()
	err = db.Table(&rows).Limit(10).Select()
	log.Println(db.LastSql())
	if err != nil {
		log.Println(err.Error())
		return
	}
	log.Println(rows)
```
生成的sql语句是正常的可以使用，但是`Select()`方法总是会返回我说的那个错误

**Comment by icefoxhz** [comment]
// 多条数据的map类型
type UserMap []gorose.Map
func (u *UserMap) TableName() string {
&nbsp; &nbsp;return "myUsers"
}




func TestOracleSelect(t *testing.T) {
&nbsp; .....
&nbsp; var u = UserMap{}
&nbsp; err = db.Table(&amp;u).Limit(1).Select()

&nbsp; .....
&nbsp;&nbsp;fmt.Println(db.LastSql())
&nbsp;&nbsp;fmt.Println(u)
}






我这样写是可以的~~&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dxvgef"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 中午11:43
收件人:&nbsp;"gohouse/gorose"<gorose@noreply.github.com&gt;;
抄送:&nbsp;"爆裂天使"<85972652@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [gohouse/gorose] 操作oracle数据库时，Limit()方法会出现错误 (#96)



 
可以使用 db.LastSql() 查看生成的 sql语句~~
 关键代码在这个地方
  	var rows []model.TestTable 	db := engin.NewOrm() 	err = db.Table(&amp;rows).Limit(10).Select() 	log.Println(db.LastSql()) 	if err != nil { 		log.Println(err.Error()) 		return 	} 	log.Println(rows)
 
生成的sql语句是正常的可以使用，但是Select()方法总是会返回我说的那个错误

**Comment by dxvgef** [comment]
改成[]gorose.map是可以了，但是多条记录只能转成map不能转成[]struct吗？

**Comment by fizzday** [comment]
@dxvgef 具体sql打印出来是什么样的

**Comment by dxvgef** [comment]
@fizzday 测试代码已经删了，不过当时生成出来的sql语句确实是正确的，只是gorose会报一个错误，而且无法获得记录集
